//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMSMint.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSMSMint.Core.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate Functions.
        /// </summary>
        public static string AggregateFunctionsNodeName {
            get {
                return ResourceManager.GetString("AggregateFunctionsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string DatabasesNodeName {
            get {
                return ResourceManager.GetString("DatabasesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string FunctionsNodeName {
            get {
                return ResourceManager.GetString("FunctionsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmability.
        /// </summary>
        public static string ProgrammabilityNodeName {
            get {
                return ResourceManager.GetString("ProgrammabilityNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar-valued Functions.
        /// </summary>
        public static string ScalarValuedFunctionsNodeName {
            get {
                return ResourceManager.GetString("ScalarValuedFunctionsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schemas.
        /// </summary>
        public static string SchemasNodeName {
            get {
                return ResourceManager.GetString("SchemasNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityNodeName {
            get {
                return ResourceManager.GetString("SecurityNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedures.
        /// </summary>
        public static string StoredProcNodeName {
            get {
                return ResourceManager.GetString("StoredProcNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms.
        /// </summary>
        public static string SynonymsNodeName {
            get {
                return ResourceManager.GetString("SynonymsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Databases.
        /// </summary>
        public static string SystemDatabasesNodeName {
            get {
                return ResourceManager.GetString("SystemDatabasesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string TablesNodeName {
            get {
                return ResourceManager.GetString("TablesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table-valued Functions.
        /// </summary>
        public static string TableValuedFunctionsNodeName {
            get {
                return ResourceManager.GetString("TableValuedFunctionsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string TypesNodeName {
            get {
                return ResourceManager.GetString("TypesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined Data Types.
        /// </summary>
        public static string UserDefinedDataTypesNodeName {
            get {
                return ResourceManager.GetString("UserDefinedDataTypesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined Table Types.
        /// </summary>
        public static string UserDefinedTableTypesNodeName {
            get {
                return ResourceManager.GetString("UserDefinedTableTypesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string ViewsNodeName {
            get {
                return ResourceManager.GetString("ViewsNodeName", resourceCulture);
            }
        }
    }
}
